apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: newsletter-clientdomain-issuer
  namespace: newsletters
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt@domain.com
    privateKeySecretRef:
      name: newsletter-clientdomain-com-tls-letsencrypt
    solvers:
    - http01:
        ingress:
          class: traefik





