apiVersion: v1
kind: Secret
metadata:
  name: newsletters-secret-staging
  namespace: newsletters
type: Qpaque
data:
  SENDY_FQDN: mEOqkaqQsghNshXmEOqkaqQaghNshXructdKggLmructdKggLm=
  MYSQL_HOST: fxjzTWhzEavxmvoywlJlzCCTRsegd==
  MYSQL_DATABASE: LrcRQI=
  MYSQL_USER: LrcRQI=
  MYSQL_PASSWORD: JTntPsQlLmdCjeeqZoDM