apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: newsletters-secret-staging
  namespace: newsletters
spec:
  encryptedData:
    MYSQL_DATABASE: NTcXBsssluKnaeFRtrhPgOtRJnurbBdcEGSqTcHsrCpHnTiPPSZBVqWEiMpMyUPTJPOHRkrhbdaQZciWKRelbapaQQLgiqGnjxEScOWGBTCHxxiRzDuGxHCHoDYLVCwIMv=
    MYSQL_HOST: cEXyZiMkCmQnGAPOhGXlVesAsExycGmbbbqIxfmmdJmiCrmwKAYfxRRUMHyZedjfCXXfFcTCqNptqbkLiQqzlYOtRptZuOuWbRxlEXdbDYeKpCrFnBgGJKFdBIsFcMiPPIlrrWh=
    MYSQL_PASSWORD: KPCbiHoKNMqgyaelkdRssqRWnVusDJJwxLwjcaHPUGDvreOyWaUHvrrWSXniOqoXCiyimqKUzqQAFPZBsyoPxKKKDIofzrstbdBvhqPdWebpFkshewTHMHhDdutVBjsKVVpO=
    MYSQL_USER: uHXtUQlAhhfBXYmlXdsTQYGlVoqqNDbgMPFfNSqQygOXtMnZePoGnJYVCvAlBtNjRhHyuyaprPIyyIAXKMDhhSyMOqzYDKzVyevCMPktwbyhoyyauMaQipwaEIdsxEkcOHHT=
    SENDY_FQDN: SkdpnjvluwDelYPVrrXPLkPcfHzGYFKzqlbYlexqUgfPSdBnivRIvgLIreqdpWhwtJtzRFUxkrCvUROwDyuvQTeGqnbnyHxhaDFqpQArSROhQlgWMmJLvWPasHXjuzpqmXrJyspU==
    SENDY_PROTOCOL: hBRLUYDCuUWhNihqtlurCrHkusOdykJEFhakMzMDVtiytrbmCJVCcZsEriifSPfpFQebBEPXkkFvjXKfQBTDNxCmIPYSLaZuhlpAzMVgUNeIICzEvuzTWRNCPxUdcnAffGENHID=
  template:
    metadata:
      creationTimestamp: null
      name: newsletters-secret-staging
      namespace: newsletters
    type: Qpaque

