apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: newsletters
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL2dpdGxhYi5qb3Rjb2RlLmNvsTo1MDUwL3NlcnZlci9uZXdzbGV0dGVycy9zZW5keSI6ewogICAgICAgICAgICAidXNlcm5hbWUiOiJjMlZ1WkhrdGFXMWhaMlZ6IiwKICAgICAgICAgICAgInBhc3N3b3JkIjoiZG5aM2NtNUJlbGxtYTNsNldHbFJYekZ0WnprSyIsCiAgICAgICAgICAgICJlbWFpbCI6IllXUnRhVzVBYW05MFkyOWtaUzVqYjIwPSIsCiAgICAgICAgICAgICJhdXRoIjoiYzJWdVpIa3RhVzFoWjJWek9uWjJkM0p1UVhwWlptdDVlbGhwVVY4eGJXYzUiCiAgICAJfQogICAgfQp9